# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:

- script: | 
    dotnet restore ApplicationSubmission.sln
    ls
  displayName: 'dotnet restore'

- script: | 
    dotnet clean ApplicationSubmission.sln
    ls
  displayName: 'dotnet clean'

- script: | 
    dotnet build ApplicationSubmission.sln --configuration Release
    ls
    cd /home/vsts/work/1/s/ApplicationSubmission/bin/Debug/netcoreapp2.1/
    ls -al
    pwd
  displayName: 'dotnet build'
  
- script: | 
    dotnet publish ApplicationSubmission.sln -o "Publish"
    ls
    cd Publish
    ls -al
    pwd
  displayName: 'dotnet build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'Publish'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    
- task: LambdaDeployFunction@1
  inputs:
    awsCredentials: 'awsconnection'
    regionName: 'ap-south-1'
    deploymentMode: 'codeonly'
    functionName: 'ApplicationSubmission'
    codeLocation: 'localfile'
    localZipFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

- task: LambdaDeployFunction@1
  inputs:
    awsCredentials: 'awsconnection'
    regionName: 'ap-south-1'
    deploymentMode: 'codeandconfiguration'
    functionName: 'ApplicationSubmission'
    functionHandler: 'ApplicationSubmission::ApplicationSubmission.LambdaEntryPoint::FunctionHandlerAsync'
    runtime: 'dotnetcore2.1'
    codeLocation: 'localfile'
    localZipFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    roleARN: 'arn:aws:iam::618393550001:role/abcdkdded-LambdaExecutionRole-1EQHS5DI463T0'
